#%RAML 1.0
title: RECS|Box Redfish API
version: 0.1.0
baseUri: http://localhost:8080/redfish
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number
  ServiceRoot: !include schemas/ServiceRoot.v1_1_1.json#/definitions/ServiceRoot
/:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "v1" : "/redfish/v1/"
              }
/v1:
  get:
    responses:
      200:
        body:
          application/json:
            type: ServiceRoot
            example: |
              {
                "v1" : "/redfish/v1/"
              }
