#%RAML 1.0
title: RECS|Box Redfish API
version: 0.1.0
baseUri: http://localhost:8080
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number
  RedfishResource: !include schemas\Resource.v1_3_0.json#definitions/Resource
/helloWorld:
  get:
    responses:
      200:
        body:
          application/json:
            type: RedfishResource
            example: |
              {
                "message2" : "Hello World"
              }
